apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-ui
  template:
    metadata:
      labels:
        app: portfolio-ui
    spec:
      containers:
      - name:  portfolio_frontend:latest
        image:  portfolio_frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
